### ISSUE TITLE
Extending scope of repository

### ISSUE THREAD

**Issue by ad-m** [tjend/repo_terraform#1]
What do you think about extending the scope of this repository to other Hashicorp projects? For me interesting is Packer, which is provided by Hashicorp in the same way - one binary file and also has no official automatic update mechanisms.

BTW. Thank you for the idea - I have developed a similar repository for Telegram, but I use GitHub Actions for periodic updates and keep everything in repository: https://github.com/ad-m/telegram-repository/

**Comment by tjend** [comment]
Hashicorp has released their own apt repo now with terraform, and suggests packer will be added soon, https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository.

As such, I'll be closing my apt repo.
